
service: s3-db

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:*"
        Resource:
          - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
          - "arn:aws:s3:::s3db-acs-1216/*"
          - "arn:aws:s3:::s3db-acs-1115/*"
          - "arn:aws:s3:::s3db-acs-1014/*"
          - "arn:aws:s3:::s3db-acs-raw-1216/*"
          - "arn:aws:s3:::s3db-acs-raw-1115/*"
          - "arn:aws:s3:::s3db-acs-raw-1014/*"
  stage: dev
  region: us-west-2
  timeout: 300

functions:
  dataparse:
    handler: dataparse.parse
    memorySize: 3006
  dataupload:
    handler: dataupload.upload
    memorySize: 1024